### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by amandahamynen** [TopiasHarjunpaa/ot-harjoitustyo#1]
Projekti ladattu 4.5. klo 16:24

- Koodin laatuvaatimuuksien kannalta koodisi on erittäin laadukasta ja helposti ymmärrettävää! 
Luokat, metodit, apumuuttujat, parametrit yms. on nimetty selkeästi ja johdonmukaisesti ja niissä on käytetty oikeaa formaattia (esim. luokat PascalCase-formaatilla, metodit snake_case…). 

- Metodit ja funktiot lisäksi noudattavat hyvin Single Responsibility -periaatetta. 

- Toistuvaa koodia en myöskään havainnut. 

- Käyttöliittymä ja sovelluslogiikka on hyvin erotettu toisistaan, enkä havainnut sovelluslogiikkaan liittyviä operaatioita käyttöliittymässä.

- Projektin rakenne on hyvä ja tiedostot on jaettu järkevällä tavalla hakemistoihin. Projektista ei myöskään löytynyt ylimääräistä tavaraa (esim. pytest- ja coverage- komentojen generoimia tiedostoja).

- Testaus myös näyttäää olevan hyvällä kantilla. Itselläni ei ole valitettavasti kokemusta pygamen käytöstä, joten testien ymmärtäminen oli hieman heikkoa omalta osin. Jotkin tiedostot (esim. audio_service_test.py ja game_service_test.py) eivät näyttäneet testaavan mitään (?). 

Itse pelistä en voi antaa sen kummemmin palautetta, sillä yrittäessäni suorittaa komentoa ’poetry run invoke build’ saan virheen ’sqlite3.OperationalError: database is locked’. Peli vaikuttaa alustavan käyttöohjeen mukaan oikein mielekkäältä ja harmittaa kovasti, etten päässyt sitä itse kokeilemaan :/ 

Kaiken kaikkiaan kurssilla esitettyjen koodin laatuvaatimusten perusteella projektisi vaikuttaa lähes tulkoon täydelliseltä jo tässä kohtaa! Erinomaista työtä!

**Comment by TopiasHarjunpaa** [comment]
Kiitos kommenteista ja positiivisesta palautteesta!

Ikävä, ettet päässyt testaamaan peliä katselmoinnin yhteydessä. En osaa sanoa mikä on mahtanut olla tuossa syynä, mutta itse havaitsin ainakin etätyöpöydällä saman ongelman, kun purin pakkauksen suoraan Downloads -kansiossa. Sen sijaan ohjelma toimii itselläni myös etätyöpöydällä siirrettyäni pakkauksen omaan Ohjelmistotekniikan kansioon. Telegram keskustelujen perusteella noita vastaavia ongelmia on ollut muillakin, joten muitakin syitä lienee olemassa.

Kommentteihin liittyen, taisin olla tuossa vaiheessa luonut tyhjät testitiedostot, joita en ollut palautuksen yhteydessä vielä kerennyt toteuttaa. Nyt noistakin pitäisi loppupalautuksen yhteydessä löytyä tavaraa. Jos vielä kiinnostaa käydä kokeilemassa, niin linkki loppupalautuksen releasee löytyy projektin README:sta.

Tsemppiä opintoihin ja mukavaa kesän alkua!

-Topias
